### ISSUE TITLE
Api calls should return more info than a boolean variable

### ISSUE THREAD

**Issue by bdonald25** [isenseDev/iSENSE-API#8]
Most of the Api calls return a boolean variable to indicate if it was successful. I want to display the error message from the server in my java api testing app.

I will fix this for Android as well.

**Comment by bdonald25** [comment]
This was fixed a while ago.

**Comment by fgmart** [comment]
Hi everyone,

Where is there documentation for these results objects?

**Comment by bdonald25** [comment]
This is not on the web side. This is on the java API side. Specifically for the java API testing application I made.

**Comment by bdonald25** [comment]
public class UploadInfo {
	public int dataSetId = -1;
	public int mediaId = -1;
	public int projectId = -1;
	public String errorMessage = "Failure";
	public Boolean success = false;
};

This was the class I made to pass back the results from the web api calls in the java api to the testing app.

**Comment by bdonald25** [comment]
The issue was the server was passing back a lot of information to the java API but the java API was only returning true or false to the testing app. I made this object to pass back some more information that the server returned. That way if it fails to upload I can get the error message or if it succeeds I can get the id of the data set or media object.

**Comment by jdalphon** [comment]
/api/v1/docs

**Comment by bdonald25** [comment]
http://isensedev.github.io/iSENSE-API/Java-iSENSE-API-1.0/doc/edu/uml/cs/isense/api/API.html - Java API docs auto generated with eclipse.

http://isensedev.github.io/iSENSE-API/Java-iSENSE-API-1.0/doc/edu/uml/cs/isense/api/UploadInfo.html
This page is for this object.
